In [17]:
import numpy as np
import gym
import torch

In [2]:
env = gym.make('PongNoFrameskip-v0')

In [3]:
action = env.action_space.sample()

In [4]:
action

1

In [7]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([1, 2, 3])
a.shape,b.shape

((2, 3), (3,))

In [6]:
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [15]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
a[np.arange(10), np.arange(10)]

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [21]:
t = torch.arange(100).view(10, 10)
torch.max(t, 1)[1]

tensor([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [24]:
a = np.linspace(-10, 10, 51)
b = np.ones([256, 1])
a.shape, b.shape, (a * b).shape

((51,), (256, 1), (256, 51))